apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eureka
  namespace: test
spec:
  replicas: 2
  serviceName: eureka
  selector:
    matchLabels:
      ekos-app: eureka
  template:
    metadata:
      labels:
        ekos-app: eureka
    spec:
      containers:
      - image: mirror.ghostcloud.cn/microservice/eureka-server:1.0
        name: eureka
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: test
spec:
  clusterIP: None
  ports:
  - name: "8761"
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    ekos-app: eureka
  type: ClusterIP
  
