apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-admin
  namespace: springcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      ekos-app: eureka-admin
  template:
    metadata:
      labels:
        ekos-app: eureka-admin
    spec:
      initContainers:
      - name: init-eureka
        image: mirror.ghostcloud.cn/microservice/eureka-admin:1.0
        command:
        - sh
        - "-c"
        - |
          set -ex
          
          PEERS=$(nslookup eureka 2>/dev/null | grep Address | awk '{print $4}' | awk '{printf("http://%s:8761/,",$1)}')
          DEFAULT_ZONE=${PEERS%,}
          arr=${DEFAULT_ZONE//,/ }
          for address in $arr; do
            info=`curl -s -m 10 --connect-timeout 10 -I $address`
              code=`echo $info|grep "HTTP"|awk '{print $2}'`
              if [ "$code" == "200" ];then
                 echo "...........................$code"
              else
                 echo "...........................$code"
                 exit 1
               fi
          done
      containers:
      - env:
        - name: DISCOVERY_SERVICE_NAME
          value: eureka
        image: mirror.ghostcloud.cn/microservice/eureka-admin:1.0
        name: eureka-admin
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-admin
  namespace: springcloud
spec:
  ports:
  - name: "7020"
    port: 7020
    protocol: TCP
    targetPort: 7020
  selector:
    ekos-app: eureka-admin
